### ISSUE TITLE
Any way to get a hold of the editor from the "outside"?

### ISSUE THREAD

**Issue by jagthedrummer** [smith-carson/ember-simplemde#10]
I'm trying to setup a `simple-mde` editor with a persistent image picker/inserter next to it. I can't figure out how to let the image picker interact with the editor from the outside.

I've already built a custom button in the editor toolbar that can open a modal which then gives me access to the editor instance, but I'd like to do something similar with a component that will always sit next to the editor.

Is there any way to make that happen?

**Comment by marceloandrader** [comment]
I'm not sure if it's possible, you can use [InboundActions](https://github.com/GavinJoyce/ember-component-inbound-actions) to hold a reference of the component and call actions on it.
